require('core.plugins')
require('core.options')
require('core.keymaps')

require('plugins.statusbar')
require('plugins.telescope')
require('plugins.neotree')
require('plugins.treesitter')
require('plugins.manson')
require('plugins.lsp')
require('plugins.cmp')
require('plugins.comment')
